version: '3'

services:
  frontend:
    command: npm run start
    stdin_open: true
    tty: true
    # ports:
    #   - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src

  api:
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src

  api:
    command: npm run dev
    volumes:
      - ./auth/src:/usr/src/app/src  

  nginx:
    volumes: 
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
          
